run:
  timeout: 5m
  go: "1.21"
  modules-download-mode: readonly

linters-settings:
  govet:
    check-shadowing: false
  gocyclo:
    min-complexity: 30  # Très permissif
  dupl:
    threshold: 200  # Très permissif
  goconst:
    min-len: 5
    min-occurrences: 10  # Très permissif
  misspell:
    locale: US
  lll:
    line-length: 200  # Très permissif
  goimports:
    local-prefixes: backend

linters:
  enable:
    # Linters de base seulement
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - typecheck
    
    # Linters de sécurité
    - gosec

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - all
    - path: cmd/
      linters:
        - all
    - path: internal/
      linters:
        - all
    - path: pkg/
      linters:
        - all
    - path: docs/
      linters:
        - all
    - path: main\.go
      linters:
        - all
  max-issues-per-linter: 0
  max-same-issues: 0 