// Noms d'icônes populaires pour chaque bibliothèque
export const IONICONS = {
  HOME: 'home',
  SETTINGS: 'settings',
  PERSON: 'person',
  SEARCH: 'search',
  ADD: 'add',
  CLOSE: 'close',
  WALLET: 'wallet',
  TRENDING_UP: 'trending-up',
  TRENDING_DOWN: 'trending-down',
  EDIT: 'create',
  DELETE: 'trash',
  CHECKMARK: 'checkmark',
  HEART: 'heart',
  STAR: 'star',
  MAIL: 'mail',
  CALL: 'call',
  BRIEFCASE: 'briefcase',
  TIME: 'time',
  CALENDAR: 'calendar',
  LOCATION: 'location',
  MENU: 'menu',
  REFRESH: 'refresh',
} as const

export const FONTAWESOME_6 = {
  HOUSE: 'house',
  GEAR: 'gear',
  USER: 'user',
  MAGNIFYING_GLASS: 'magnifying-glass',
  PLUS: 'plus',
  XMARK: 'xmark',
  WALLET: 'wallet',
  MONEY_BILL: 'money-bill',
  CHART_LINE: 'chart-line',
  CHART_BAR: 'chart-bar',
  PEN: 'pen',
  TRASH: 'trash',
  HEART: 'heart',
  STAR: 'star',
  ENVELOPE: 'envelope',
  PHONE: 'phone',
  BRIEFCASE: 'briefcase',
  CLOCK: 'clock',
  CALENDAR: 'calendar',
  LOCATION_DOT: 'location-dot',
  BARS: 'bars',
  ARROWS_ROTATE: 'arrows-rotate',
  ARROW_TRENDING_UP: 'arrow-trending-up',
  ARROW_TRENDING_DOWN: 'arrow-trending-down',
  MONEY_BILL_TREND_UP: 'money-bill-trend-up',
  RECEIPT: 'receipt',
  BUILDING_COLUMNS: 'building-columns',
  CHEVRON_DOWN: 'chevron-down',
  CHEVRON_UP: 'chevron-up',
  CHECK: 'check',
  // Icônes financières
  PIGGY_BANK: 'piggy-bank',
  UNIVERSITY: 'university',
  DOLLAR_SIGN: 'dollar-sign',
  EURO_SIGN: 'euro-sign',
  STERLING_SIGN: 'sterling-sign',
  YEN_SIGN: 'yen-sign',
  FRANC_SIGN: 'franc-sign',
  COINS: 'coins',
  CREDIT_CARD: 'credit-card',
  MONEY_BILL_WAVE: 'money-bill-wave',
  HAND_HOLDING_DOLLAR: 'hand-holding-dollar',
  CHART_PIE: 'chart-pie',
  CALCULATOR: 'calculator',
  // Icônes de catégories
  UTENSILS: 'utensils',
  CAR: 'car',
  GAMEPAD: 'gamepad',
  HEART_PULSE: 'heart-pulse',
  SHOPPING_BAG: 'shopping-bag',
  GRADUATION_CAP: 'graduation-cap',
  ELLIPSIS: 'ellipsis',
} as const

// FontAwesome 5
export const FONTAWESOME_5 = {
  // Icônes financières
  PIGGY_BANK: 'piggy-bank',
  UNIVERSITY: 'university',
  DOLLAR_SIGN: 'dollar-sign',
  EURO_SIGN: 'euro-sign',
  STERLING_SIGN: 'sterling-sign',
  YEN_SIGN: 'yen-sign',
  FRANC_SIGN: 'franc-sign',
  COINS: 'coins',
  CREDIT_CARD: 'credit-card',
  MONEY_BILL: 'money-bill',
  MONEY_BILL_WAVE: 'money-bill-wave',
  HAND_HOLDING_USD: 'hand-holding-usd',
  CHART_LINE: 'chart-line',
  CHART_BAR: 'chart-bar',
  CHART_PIE: 'chart-pie',
  CALCULATOR: 'calculator',
  // Icônes de catégories
  UTENSILS: 'utensils',
  CAR: 'car',
  GAMEPAD: 'gamepad',
  SHOPPING_BAG: 'shopping-bag',
  GRADUATION_CAP: 'graduation-cap',
  ELLIPSIS: 'ellipsis',
  // Icônes de base
  HOME: 'home',
  USER: 'user',
  SEARCH: 'search',
  PLUS: 'plus',
  TIMES: 'times',
  CHECK: 'check',
  HEART: 'heart',
  STAR: 'star',
  ENVELOPE: 'envelope',
  PHONE: 'phone',
  BRIEFCASE: 'briefcase',
  CLOCK: 'clock',
  CALENDAR: 'calendar',
  CALENDAR_ALT: 'calendar-alt',
  MAP_MARKER_ALT: 'map-marker-alt',
  BARS: 'bars',
  ELLIPSIS_V: 'ellipsis-v',
  SYNC: 'sync',
  DOWNLOAD: 'download',
  UPLOAD: 'upload',
} as const

// MaterialCommunityIcons
export const MATERIAL_COMMUNITY_ICONS = {
  // Icônes financières
  CELLPHONE: 'cellphone',
  CASH: 'cash',
  CASH_MULTIPLE: 'cash-multiple',
  CASH_REGISTER: 'cash-register',
  BANK: 'bank',
  BANK_OUTLINE: 'bank-outline',
  CREDIT_CARD: 'credit-card',
  CREDIT_CARD_OUTLINE: 'credit-card-outline',
  WALLET: 'wallet',
  WALLET_OUTLINE: 'wallet-outline',
  COINS: 'coins',
  CURRENCY_USD: 'currency-usd',
  CURRENCY_EUR: 'currency-eur',
  CURRENCY_GBP: 'currency-gbp',
  CURRENCY_JPY: 'currency-jpy',
  CURRENCY_CHF: 'currency-chf',
  CHART_LINE: 'chart-line',
  CHART_BAR: 'chart-bar',
  CHART_PIE: 'chart-pie',
  CALCULATOR: 'calculator',
  // Icônes de base
  HOME: 'home',
  HOME_OUTLINE: 'home-outline',
  ACCOUNT: 'account',
  ACCOUNT_OUTLINE: 'account-outline',
  MAGNIFY: 'magnify',
  PLUS: 'plus',
  CLOSE: 'close',
  CHECK: 'check',
  HEART: 'heart',
  HEART_OUTLINE: 'heart-outline',
  STAR: 'star',
  STAR_OUTLINE: 'star-outline',
  EMAIL: 'email',
  EMAIL_OUTLINE: 'email-outline',
  PHONE: 'phone',
  BRIEFCASE: 'briefcase',
  BRIEFCASE_OUTLINE: 'briefcase-outline',
  CLOCK: 'clock',
  CLOCK_OUTLINE: 'clock-outline',
  CALENDAR: 'calendar',
  CALENDAR_OUTLINE: 'calendar-outline',
  MAP_MARKER: 'map-marker',
  MAP_MARKER_OUTLINE: 'map-marker-outline',
  MENU: 'menu',
  DOTS_VERTICAL: 'dots-vertical',
  REFRESH: 'refresh',
  DOWNLOAD: 'download',
  UPLOAD: 'upload',
} as const

export type IoniconsName = typeof IONICONS[keyof typeof IONICONS]
export type FontAwesome6Name = typeof FONTAWESOME_6[keyof typeof FONTAWESOME_6]
export type FontAwesome5Name = typeof FONTAWESOME_5[keyof typeof FONTAWESOME_5]
export type MaterialCommunityIconsName = typeof MATERIAL_COMMUNITY_ICONS[keyof typeof MATERIAL_COMMUNITY_ICONS]
export type IconName = IoniconsName | FontAwesome6Name | FontAwesome5Name | MaterialCommunityIconsName 