export const defaultIcons = [
    { name: "Cash", icon: "fa:money" },
    { name: "Compte Bancaire", icon: "fa:university" },
    { name: "Mobile Money", icon: "mc:cellphone" },
    { name: "Orange Money", icon: "fa:mobile" },
    { name: "MTN MOMO", icon: "fa:mobile" },
    { name: "Épargne", icon: "fa:piggy-bank" },
    { name: "Carte de Crédit", icon: "fa:credit-card" },
    { name: "Compte Salaire", icon: "md:work" },
    { name: "Investissements", icon: "fa:chart-line" },
    { name: "Crypto Wallet", icon: "mc:bitcoin" },
    { name: "Santé", icon: "fa5:heartbeat" },
    { name: "Transport", icon: "fa:car" },
    { name: "Shopping", icon: "fa:shopping-bag" },
    { name: "Éducation", icon: "fa:graduation-cap" },
    { name: "Maison", icon: "fa:home" },
    { name: "Électricité", icon: "fa:bolt" },
    { name: "Eau", icon: "fa5:tint" },
    { name: "Internet", icon: "fa5:wifi" },
    { name: "Loisirs", icon: "fa:gamepad" },
    { name: "Voyages", icon: "fa:plane" },
]
