# Configuration de production pour MeshaPlus Backend
# Utilise les services locaux (PostgreSQL, Redis) au lieu de Docker

server:
  port: 8080
  host: "0.0.0.0"
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 60s

database:
  driver: "postgres"
  host: "localhost"
  port: 5432
  name: "meshaplus"
  user: "postgres"
  password: "postgres"
  sslmode: "disable"
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime: "5m"

redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0
  pool_size: 10
  min_idle_conns: 5

jwt:
  secret: "your-super-secret-jwt-key-change-in-production"
  expiration: "24h"
  refresh_expiration: "168h"

storage:
  type: "local"
  local:
    path: "/opt/meshaplus/uploads"
    max_file_size: "10MB"
    allowed_extensions: ["jpg", "jpeg", "png", "gif", "pdf", "doc", "docx"]

logging:
  level: "info"
  format: "json"
  output: "stdout"
  file:
    enabled: true
    path: "/var/log/meshaplus/app.log"
    max_size: "100MB"
    max_age: "30d"
    max_backups: 10

cors:
  allowed_origins: ["*"]
  allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
  allowed_headers: ["*"]
  allow_credentials: true
  max_age: "12h"

security:
  bcrypt_cost: 12
  rate_limit:
    enabled: true
    requests_per_minute: 100
    burst: 20

features:
  swagger:
    enabled: true
    path: "/swagger"
  health_check:
    enabled: true
    path: "/api/v1/health"
  metrics:
    enabled: false
    path: "/metrics"

environment: "production" 